input {
  tcp {
    port => 5044
    codec => json_lines
  }
}

filter {
  if [timestamp] {
    date {
      match => ["timestamp", "ISO8601"]
      target => "@timestamp"
    }
  }
  mutate {
    add_field => { "observability_source" => "banking-lab" }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "banking-logs-%{+YYYY.MM.dd}"
  }
  stdout { codec => rubydebug }
}
